name: Security Advisory
description: File a bug report
title: "[Security Advisory]: "
labels: ["security", "advisory"]
projects:
assignees:
body:
  - type: markdown
    attributes:
    value: |
      Complete this form to file a security advisory
