name: Security Advisory
description: File a Security Advisory
title: "[Security Advisory]: "
labels: ["security", "advisory"]
body:
  - type: markdown
    attributes:
      value: |
        Please complete all sections to file a security advisory!
  - type: textarea
    id: desc
    attributes:
      label: Security Advisory Description
      description: Please address the vulnerability, which repo it addresses, etc
      placeholder: Tell us what you see!
      value: "This security advisory..."
    validations:
      required: true
    - type: markdown
    attributes:
      value: |
        Please complete all sections to file a security advisory!
