name: Security Advisory
description: File a Security Advisory
title: "[Security Advisory]: "
labels: ["security", "advisory"]
projects: []
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        Please complete all sections to file a security advisory!
  - type: textarea
    id: desc
    attributes:
      label: Security Advisory Description
      description: Please address the vulnerability, which repo it addresses, etc
      placeholder: Tell us what you see!
      value: "This security advisory..."
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Security Advisory Impact
      description: Describe the impact of the vulnerability this advisory addresses
      placeholder: Tell us what you see!
      value: "The impact..."
    validations:
      required: true
- type: textarea
    id: workaround
    attributes:
      label: Security Advisory Workaround(s)
      description: Describe the workaround(s) for this vulnerability
      placeholder: Tell us what you see!
      value: "The workaround(s)..."
    validations:
      required: true
- type: textarea
    id: more
    attributes:
      label: Security Advisory Additional Information
      description: Additional information for the vulnerability this advisory addresses
      placeholder: Tell us what you see!
      value: "See 1..."
      value: "See 2..."
    validations:
      required: true
