name: Security Advisory
description: File a Security Advisory
title: "[Security Advisory]: "
labels: ["security", "advisory"]
body:
  - type: markdown
    attributes:
      value: |
        Please complete all sections of this template to file a security advisory!
  - type: textarea
    id: desc
    attributes:
      label: Description
      description: Describe the security advisory vulnerability
      placeholder: Tell us what you see!
      value: "The vulnerability..."
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe the security advisory impact
      placeholder: Tell us what you see!
      value: "The impact..."
    validations:
      required: true
  - type: textarea
    id: workarounds
    attributes:
      label: Workarounds
      description: Describe the security advisory workarounds, if any
      placeholder: Tell us what you see!
      value: "The workarounds..."
    validations:
      required: true
  - type: textarea
    id: cvss
    attributes:
      label: CVSS 3.1 Score and Vector/Tuple
      description: CVSS 3.1 Score and Vector/Tuple
      placeholder: Tell us what you see!
      value: |
        Using https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator score this advisory and insert here.
        Example:
                 CVSS Score: 5.1
                 CVSS Vector: AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:L/E:U/RL:X/RC:X"
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Information
      description: Additional Information
      placeholder: Tell us what you see!
      value: "Additional information..."
    validations:
      required: true
