name: Security Advisory
description: File a Security Advisory
title: "[Security Advisory]: "
labels: ["security", "advisory"]
body:
  - type: markdown
    attributes:
      value: |
        Please complete all sections of this template to file a security advisory!
  - type: textarea
    id: desc
    attributes:
      label: Description
      description: Describe the security advisory vulnerability
      placeholder: Tell us what you see!
      value: "The vulnerability..."
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe the security advisory impact
      placeholder: Tell us what you see!
      value: "The impact..."
    validations:
      required: true
  - type: textarea
    id: workarounds
    attributes:
      label: Workarounds
      description: Describe the security advisory workarounds, if any
      placeholder: Tell us what you see!
      value: "The workarounds..."
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Information
      description: Additional Information
      placeholder: Tell us what you see!
      value: "Additional information..."
    validations:
      required: true
