name: Security Advisory
description: File a Security Advisory
title: "[Security Advisory]: "
labels: ["security", "advisory"]
body:
  - type: markdown
    attributes:
      value: |
        Please complete all sections of this template to file a security advisory!
  - type: textarea
    id: package
    attributes:
      label: Package and Versions
      description: Describe the package, affected version(s), and patched version
      placeholder: Tell us what you see!
      value: |
        Package:  
        Affected Version(s):  
        Patched Version(s):  
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: Description
      description: Describe the security advisory vulnerability
      placeholder: Tell us what you see!
      value: "The vulnerability..."
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe the security advisory impact
      placeholder: Tell us what you see!
      value: "The impact..."
    validations:
      required: true
  - type: textarea
    id: patches
    attributes:
      label: Patches
      description: Describe the security advisory patche(s)
      placeholder: Tell us what you see!
      value: "The patch..."
    validations:
      required: true
  - type: textarea
    id: workarounds
    attributes:
      label: Workarounds
      description: Describe the security advisory workarounds, if any
      placeholder: Tell us what you see!
      value: "The workarounds..."
    validations:
      required: true
  - type: textarea
    id: cvss
    attributes:
      label: CVSS 3.1 Score and Vector
      description: Using https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator score this advisory and insert below
      placeholder: Tell us what you see!
      value: |
        Example:
                   CVSS Score: 5.1
                   CVSS Vector: AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:L/E:U/RL:X/RC:X
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Information
      description: Additional Information
      placeholder: Tell us what you see!
      value: "Additional information..."
    validations:
      required: true
